//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SanPham
    {
        public int MaSP { get; set; }
        public int Dai { get; set; }
        public int Rong { get; set; }
        public int Cao { get; set; }
        public int TrongLuong { get; set; }
        public string HeDieuHanh { get; set; }
        public string MoTa { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
